# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bcfoverparRcppClean <- function(y_, Omega_con, Omega_mod, Omega_con_est, Omega_mod_est, x_con_, x_mod_, x_con_est_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, Sigma0_con, Sigma0_mod, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, prior_sample = FALSE, use_con_scale = TRUE, use_mod_scale = TRUE, con_scale_df = 1, mod_scale_df = -1, status_interval = 100L, linear_mod = TRUE, linear_con = TRUE, save_trees = TRUE, dart = FALSE, g_con = 1L, g_mod = 1L, var_sizes_con = as.numeric( c(0.0)), var_sizes_mod = as.numeric( c(0.0))) {
    .Call('_lbart_bcfoverparRcppClean', PACKAGE = 'lbart', y_, Omega_con, Omega_mod, Omega_con_est, Omega_mod_est, x_con_, x_mod_, x_con_est_, x_mod_est_, x_con_info_list, x_mod_info_list, random_des, random_var, random_var_ix, random_var_df, burn, nd, thin, ntree_mod, ntree_con, lambda, nu, Sigma0_con, Sigma0_mod, con_alpha, con_beta, mod_alpha, mod_beta, treef_name_, prior_sample, use_con_scale, use_mod_scale, con_scale_df, mod_scale_df, status_interval, linear_mod, linear_con, save_trees, dart, g_con, g_mod, var_sizes_con, var_sizes_mod)
}

lbartRcpp <- function(y_, Omega_con, Omega_con_est, x_con_, x_con_est_, x_con_info_list, burn, nd, thin, ntree_con, lambda, nu, Sigma0_con, con_alpha, con_beta, treef_name_, prior_sample = FALSE, use_con_scale = TRUE, con_scale_df = 1, status_interval = 100L) {
    .Call('_lbart_lbartRcpp', PACKAGE = 'lbart', y_, Omega_con, Omega_con_est, x_con_, x_con_est_, x_con_info_list, burn, nd, thin, ntree_con, lambda, nu, Sigma0_con, con_alpha, con_beta, treef_name_, prior_sample, use_con_scale, con_scale_df, status_interval)
}

